# Server
server:
  name: node-app
  port: 8888
  developmentMode: false
  environment: dev
  viewEngine: ejs

# Database config
db:
  host: localhost
  user: example
  password: example
  database: example
  connectionLimit: 100
  multipleStatements: true
